### PR TITLE
global: item changes indexing

### PR DESCRIPTION
**Pull request by mvesper**
* Indexes item changes after executing a receiver action.

### CODE REVIEW

**Review by david-caro — COMMENTED** [review]
Looks ok to me, though you might want to split in two commits (one with the packaging fixes and another with the indexing).

**Comment by mvesper** [comment]
@david-caro ok, see https://github.com/inveniosoftware/invenio-circulation/pull/61 :)

**Comment by david-caro** [comment]
:+1: Looks good to me (once rebased ;) )

**Comment by egabancho** [comment]
LGTM

**Comment by jirikuncar** [comment]
@mvesper is it still WIP?

**Comment by mvesper** [comment]
@jirikuncar nope :)

**Comment by jirikuncar** [comment]
LGTM

**Pull request merged**
